### ISSUE TITLE
Publish this project on pypi, please

### ISSUE THREAD

**Issue by gtxx3600** [eosnewyork/eospy#16]
This is the only usable Python EOS library I found.  You guys have done some really good works here.

**Comment by deckb** [comment]
Thank you for the compliment. I have had a task to publish to pypi will see if I can get it worked out this week.

**Comment by deckb** [comment]
Finally had a minute to do this. I had to rename the pip package to `libeospy` but everything else should stay the same.

https://pypi.org/project/libeospy/
