### ISSUE TITLE
verify function in EOSKey may always get a "True" result

### ISSUE THREAD

**Issue by gtxx3600** [eosnewyork/eospy#17]
The "verify" function in [eospy/keys.py](https://github.com/eosnewyork/eospy/blob/master/eospy/keys.py#L189) uses the "recovered" public key from signature to verify the signature itself. This means we will always get a True result no matter the signature was generated from which private key.

I think that your intention here is to use the VerifyKey from EOSKey itself to verify the digest.
```Python
def verify(self, encoded_sig, digest) :
    ''' '''
    # remove SIG_ prefix
    encoded_sig = encoded_sig[4:]
    # remove curve prefix
    curvePre = encoded_sig[:3].strip('_')
    if curvePre != 'K1' :
        raise TypeError('Unsupported curve prefix {}'.format(curvePre))

    decoded_sig = self._check_decode(encoded_sig[3:], curvePre)
    # use sig
    sig = decoded_sig[2:]
    # verify sig
    return self._vk.verify_digest(unhexlify(sig), unhexlify(digest), sigdecode=ecdsa.util.sigdecode_string)
```

**Comment by deckb** [comment]
Great call. Will fix this in the next update.
