### ISSUE TITLE
sign error with long memo

### ISSUE THREAD

**Issue by clanet** [eosnewyork/eospy#18]
If  memo's length is great then 95 , push_transaction would got error 'unsatisfied_authorization' .

**Comment by clanet** [comment]
fix this bug at types.py .
data_len = self._encode_buffer(Byte(len(self.data)/2))
==>
data_len = self._encode_buffer(VarUInt(int(len(self.data)/2)))

**Comment by deckb** [comment]
Thank you for reporting and apologizes for taking so long to fix. Should be good using version v1.1.7
