### ISSUE TITLE
Bad Gateway for url: https://api.eosnewyork.io/v1/chain/get_info

### ISSUE THREAD

**Issue by firepol** [eosnewyork/eospy#2]
Hi, I'm trying to use your library, using your examples.

OS : Ubuntu Linux
Python: 3.6.5

When I `run pycleos --url https://api.eosnewyork.io get info`
I get:

> Traceback (most recent call last):
>   File "/home/paul/env/eos-playground/bin/pycleos", line 11, in <module>
>     load_entry_point('eospy==1.0.3', 'console_scripts', 'pycleos')()
>   File "/home/paul/env/eos-playground/lib/python3.6/site-packages/eospy/command_line.py", line 73, in cleos
>     pp.pprint(ce.get_info())
>   File "/home/paul/env/eos-playground/lib/python3.6/site-packages/eospy/cleos.py", line 57, in get_info
>     return self.get('chain.get_info')
>   File "/home/paul/env/eos-playground/lib/python3.6/site-packages/eospy/cleos.py", line 23, in get
>     return cmd.get_url(url, **kwargs)
>   File "/home/paul/env/eos-playground/lib/python3.6/site-packages/eospy/dynamic_url.py", line 34, in get_url
>     r.raise_for_status()
>   File "/home/paul/env/eos-playground/lib/python3.6/site-packages/requests/models.py", line 939, in raise_for_status
>     raise HTTPError(http_error_msg, response=self)
> requests.exceptions.HTTPError: 502 Server Error: Bad Gateway for url: https://api.eosnewyork.io/v1/chain/get_info

Can you update your examples with a working URL? Or publish a list where to get those URLs?

For the url, I tried to use one found at https://eosnodes.privex.io/

E.g. http://node1.eosnewyork.io:6987

(I tried also with https, but then it hangs, nothing happens, I have to kill the program).

Please update the readme with working examples and more info, thanks.

**Comment by deckb** [comment]
I will update the examples with a list of endpoints. In the meantime you can use this list.

https://www.eosdocs.io/resources/apiendpoints/

**Comment by firepol** [comment]
Thank you. I tried the first in the list and it worked. You may also share the list in the readme, could be useful. Cheers
