### ISSUE TITLE
how to remove time in keys.sign()

### ISSUE THREAD

**Issue by bbboyjan** [eosnewyork/eospy#23]
`            k = ecdsa.rfc6979.generate_k(self._sk.curve.generator.order(),
                                         self._sk.privkey.secret_multiplier,
                                         hashlib.sha256,
                                         bytearray(sha256(digest + struct.pack('d', time.time())), 'utf-8')
                                         # use time to randomize
                                         )`
hi！ 
if i do'nt want to use time to randomize ，how to modify?

**Comment by deckb** [comment]
Sorry I missed this issue. What would you like to use to randomize? I could look into adding additional randomness or providing your own seed.
