### ISSUE TITLE
get transaction is failing?

### ISSUE THREAD

**Issue by chitrarthlav** [eosnewyork/eospy#26]
Trying to execute "get transaction --transaction TRANSACTION" command by receive the following errors:

`Traceback (most recent call last):
  File "/home/chitrarth/envs/eospy/bin/pycleos", line 11, in <module>
    sys.exit(cleos())
  File "/home/chitrarth/envs/eospy/local/lib/python2.7/site-packages/eospy/command_line.py", line 123, in cleos
    console_print(ce.get_transaction(args.transaction, timeout=args.timeout))
  File "/home/chitrarth/envs/eospy/local/lib/python2.7/site-packages/eospy/cleos.py", line 122, in get_transaction
    return self.post('history.get_transaction', params=None, json={'id': trans_id}, timeout=timeout)
  File "/home/chitrarth/envs/eospy/local/lib/python2.7/site-packages/eospy/cleos.py", line 31, in post
    return cmd.post_url(url, **kwargs)
  File "/home/chitrarth/envs/eospy/local/lib/python2.7/site-packages/eospy/dynamic_url.py", line 43, in post_url
    raise requests.exceptions.HTTPError('Error: {}'.format(r.json()))
requests.exceptions.HTTPError: Error: {u'message': u'Not Found', u'code': 404, u'error': {u'what': u'unspecified', u'code': 0, u'name': u'exception', u'details': [{u'line_number': 298, u'message': u'Unknown Endpoint', u'method': u'handle_http_request', u'file': u'http_plugin.cpp'}]}}`

**Comment by matthewborish** [comment]
Failing for me too. 

![image](https://user-images.githubusercontent.com/25910907/51451746-a1dcb880-1ceb-11e9-8a48-2b006db5c849.png)


![image](https://user-images.githubusercontent.com/25910907/51451876-52e35300-1cec-11e9-93b9-841f0350a14d.png)

**Comment by deckb** [comment]
That is an issue with the eosnewyork.io nodeos endpoint.  While we have been updating our infrastructure we have taken down the history plugin. I have updated the latest version of pycleos to point to https://proxy.eosnode.tools. This is a proxy url which will give you the lowest latency node based on your location. We suggest you use that for your querying needs.
