### ISSUE TITLE
When do you plan to provide support to trigger EOS contract?

### ISSUE THREAD

**Issue by ShilazTech** [eosnewyork/eospy#28]
When do you plan to provide support to trigger EOS contract?

e.g. I want to send a trx to EOSBet. Can I do that now or you will ad that functionalities later

**Comment by ShilazTech** [comment]
That is very good news. I will work on it from tomorrow. And will let you know how it goes. Thanks for your prompt reply.

**Comment by deckb** [comment]
No problem. I'll leave this issue open if you have any questions.

**Comment by ShilazTech** [comment]
You can pls close this issue.
