### ISSUE TITLE
'error': {'code': 3080004, 'name': 'tx_cpu_usage_exceeded'

### ISSUE THREAD

**Issue by ShilazTech** [eosnewyork/eospy#33]
My account has enough CPU but I am receving this message very often. How can I avoid this?

requests.exceptions.HTTPError: Error: {'code': 500, 'message': 'Internal Service Error', 'error': {'code': 3080004, 'name': 'tx_cpu_usage_exceeded', 'what': 'Transaction exceeded the current CPU usage limit imposed on the transaction', 'details': [{'message': 'billed CPU time (2139 us) is greater than the maximum billable CPU time for the transaction (0 us)', 'file': 'transaction_context.cpp', 'line_number': 520, 'method': 'validate_cpu_usage_to_bill'}]}}

**Comment by deckb** [comment]
That error is from nodeos and is implying that you do not have enough resources staked. When you view your account do you have more than 2139 us of CPU?

**Comment by deckb** [comment]
I'm not really sure what to tell you. The cpu is calculated by nodeos and you can see the error in the code here: https://github.com/EOSIO/eos/blob/3fddb727b8f3615917707281dfd3dd3cc5d3d66d/libraries/chain/transaction_context.cpp#L517

**Comment by ShilazTech** [comment]
From below code I can know my cpu. How can I use this information to stop my program before the above limit triggers

ce = eospy.cleos.Cleos(url='https://proxy.eosnode.tools')
acnt=ce.get_account("gi2dimrtgmge")
cpu=acnt["cpu_limit"]
print(ce.get_account("gi2dimrtgmge"))
print(cpu)

**Comment by ShilazTech** [comment]
I made below code to monitor and hold the trx till cpu recovers:

def cpumonitor():
    success=0
    while success==0:
        minrcpu=2.139
        acnt=ce.get_account("gi2dimrtgmge")
        cpu=acnt["cpu_limit"]
        avblcpu=cpu["available"]
        posstrx=avblcpu/minrcpu
        trxTH=100
        if posstrx>trxTH:
            success=1
            print("Enough CPU Available : Go Ahead with trx")
        else:
            print(ce.get_account("gi2dimrtgmge"))
            print("CPU Data ", cpu)
            print("Available CPU  ", avblcpu)
            time.sleep(3)
Seems to work so far. Let's see

**Comment by deckb** [comment]
Makes sense.
