### ISSUE TITLE
How to get the signature to send in memo

### ISSUE THREAD

**Issue by ShilazTech** [eosnewyork/eospy#35]
I need to send in signature and other fields  in memo as provided by scatter to trigger trustdicewin contract. A typical memo from scatter for trustdicewin is 

> memo under-50-951d93bc7cb5ac1e480b991cac61348050e0faa831de337aaecef08eee6f7213-d142c9101ee4b569486d3c6e50e437f2c7c99410-1549217121-0-lynxtrustdic-SIG_K1_K4QdxaLFagCvwj7rFJqqNmzh272AyKbCdeh57uH8A5KsmpA4ikT4dao59XJAa55EJQrJQLbccGdtAynMAWp1rRfT6enTeJ

I tried to build memo for trustdicewin - but I get below error. How to do that please?

 raise requests.exceptions.HTTPError('Error: {}'.format(r.json()))
requests.exceptions.HTTPError: Error: {'code': 500, 'message': 'Internal Service Error', 'error': {'code': 3050003, 'name': 'eosio_assert_message_exception', 'what': 'eosio_assert_message assertion failure', 'details': [{'message': 'assertion failure with message: memo has more than 256 bytes', 'file': 'wasm_interface.cpp', 'line_number': 917, 'method': 'eosio_assert'}, {'message': 'pending console output: ', 'file': 'apply_context.cpp', 'line_number': 72, 'method': 'exec_one'}]}}

**Comment by deckb** [comment]
It has been brought to my attention when sharing this issue that your stacktrace appears to be showing that you are trying to game the eosbetadmin contract. I cannot in continue to help you attempting to game a dapp. I will be closing all of your issues and not responding to your issues further.

**Comment by ShilazTech** [comment]
There is no attempt to game any dapp but I was trying to make a robotic betting app using AI. If that is interpreted as gaming then I am surprised.

I request you to reconsider your position.
