### ISSUE TITLE
Please give an example push action

### ISSUE THREAD

**Issue by zwca** [eosnewyork/eospy#39]
Please give an example push action,thanks.

such as：https://www.eosabc.io/luckyDraw

eosabciodice -> luckybox
[
  {
    "account" : "eosabciodice",
    "data" : {
      "name" : "eos123eos123"
    },
    "authorization" : [
      {
        "actor" : "eos123eos123",
        "permission" : "active"
      }
    ],
    "name" : "luckybox"
  }
]

**Comment by deckb** [comment]
```
arguments = {
            "name": "eos123eos123"
        }
payload = {
        "account": "eosabciodice",
        "name": "luckybox",
        "authorization": [{
            "actor": "eos123eos123",
            "permission": "active",
        }],
    }
```

See the push_transaction.py example in the example directory for how to push the transaction.

https://github.com/eosnewyork/eospy/blob/master/examples/push_transaction.py

**Comment by zwca** [comment]
thanks!
I just followed the code above and didn't have any results.

**Comment by zwca** [comment]
import eospy.cleos
import os
# this url is to a testnet that may or may not be working.
# We suggest using a different testnet such as kylin or jungle
# 
ce = eospy.cleos.Cleos(url='https://api.eosbeijing.one')
key = "5K1WPz234234342TtB8A2342TnKcEgC"
arguments = {
            "name": "eos123eos123"
            }
payload = {
        "account": "eosabciodice",
        "name": "luckybox",
        "authorization": [{
            "actor": "eos123eos123",
            "permission": "active",
        }],
    }
#Converting payload to binary
data=ce.abi_json_to_bin(payload['account'],payload['name'],arguments)
#Inserting payload binary form as "data" field in original payload
payload['data']=data['binargs']
#final transaction formed
trx = {"actions": [payload]}


This is my code,Key is false, please ignore

**Comment by deckb** [comment]
Is that all of the code? It doesn't look like you are pushing the transaction. You should have something like at the end.
```
resp = ce.push_transaction(trx, key, broadcast=True)
```

**Comment by zwca** [comment]
Thank you for your answer！ thanks
