### ISSUE TITLE
can not work on python 3.6

### ISSUE THREAD

**Issue by hmilymb** [eosnewyork/eospy#4]
push_transaction.py	
this file only work on python 2.7 ?

**Comment by deckb** [comment]
There is an issue with 3.x with signing transactions. I will be working on that issue very soon.

**Comment by hmilymb** [comment]
thanks ,
why not use sign_transaction api? it not safety for public network?

**Comment by hmilymb** [comment]
Thank you for your hardworking。
i will try for soon and reply the result

**Comment by lovewin-io** [comment]
thanks you , it is ok on linux  and window with version 3.6

**Comment by hmilymb** [comment]
it is ok in 3.6，thank you very much。
