### ISSUE TITLE
Can't import any sub-modules from eospy

### ISSUE THREAD

**Issue by IanQS** [eosnewyork/eospy#40]
# Recreating

1) Made a new virtualenv running `python3.6`

2) Ran `pip install pip install git+https://github.com/eosnewyork/eospy.git@v1.1.10`

which reported

```
Collecting git+https://github.com/eosnewyork/eospy.git@v1.1.10
  Cloning https://github.com/eosnewyork/eospy.git (to revision v1.1.10) to /tmp/pip-req-build-0omunv9h
Requirement already satisfied: pip in /home/itq/.virtualenvs/gyftie/lib/python3.6/site-packages (19.0.3)
Collecting install
  Could not find a version that satisfies the requirement install (from versions: )
No matching distribution found for install
```

3) Ran

`pip install libeospy` which ran without errors and reported

```
Successfully built libeospy pyyaml
Installing collected packages: idna, urllib3, certifi, chardet, requests, base58, ecdsa, iso8601, translationstring, colander, pytz, six, pyyaml, libeospy
Successfully installed base58-1.0.3 certifi-2019.3.9 chardet-3.0.4 colander-1.7.0 ecdsa-0.13 idna-2.8 iso8601-0.1.12 libeospy-1.1.10 pytz-2018.9 pyyaml-5.1 requests-2.21.0 six-1.12.0 translationstring-1.3
urllib3-1.24.1
```

4) Tried to run 

`from eospy.types import Abi` which reported

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'Abi'
```

# Notes
I'm not sure why it's behaving this way. Navigating into the `site-packages/eospy` in `.virtualenvs` shows that I have the following files:

```
cleos.py  
command_line.py  
dynamic_url.py  
exceptions.py  
__init__.py 
 keys.py  
__pycache__  
schema.py  
testeos.py  
types.py  
utils.py 
 __version__.py
```

**Comment by deckb** [comment]
This is weird but for some reason 1.1.10 did not have the ABI changes (even though I swore I made the change. I have created a release called 1.1.11 that has the change and it should work if you update. 

The issue you had in step 2 looks to be because you had duplicate `pip install`. Try running:
`pip install git+https://github.com/eosnewyork/eospy.git@v1.1.11`

**Comment by IanQS** [comment]
sweet! Works now, thanks!
