### ISSUE TITLE
Do you have security problems using abi_json_to_bin in your code?

### ISSUE THREAD

**Issue by xiangxn** [eosnewyork/eospy#42]
Do you have security problems using abi_json_to_bin in your code?

**Comment by deckb** [comment]
I'm not sure exactly what security problems there would be. Do you have any more info or thoughts?

**Comment by xiangxn** [comment]
The API service can modify the source content of the encoding.

**Comment by deckb** [comment]
There is a degree of trust if using an endpoint you do not own. I suggest querying a BPs endpoint or your own in the near term. The next version of eospy (2.0.0) will not need the `abi_json_to_bin` call so it will not be a concern. I will leave this issue open and report back when it is released.

**Comment by deckb** [comment]
I have finally had a chance to use abi files to serialize a transaction. This is very rudimentary as of commit https://github.com/eosnewyork/eospy/commit/ae7c6cc3aa0e85a4f78c13eaaa3f2672e1474b66 and has only been tested using eosio.system.abi and eosio.token.abi. Closing this for now.
