### ISSUE TITLE
Create multisig account

### ISSUE THREAD

**Issue by amitsharma8891** [eosnewyork/eospy#44]
Hi,

I am trying to create multisig account, for that, we need 2 public and private key to import them into the wallet.

Do you have any plan to add multisig functionality if no can you help me to understand with the following questions:

1. To create multisig account we need both public and private key and can be used as active and owner key,  how to get the public and private keys (We can get the keys by using cleos command `./cleos create key --to-console`) ?
2. How to manage a wallet? As  we have to import the private keys.

**Comment by deckb** [comment]
the eospy library already supports multisig account creation. If you look at this part at the  [newaccount](https://github.com/eosnewyork/eospy/blob/c9b49f727e952a742902df9ba098dc6e21cdeb5e/eospy/cleos.py#L218) you could modify [this part](https://github.com/eosnewyork/eospy/blob/c9b49f727e952a742902df9ba098dc6e21cdeb5e/eospy/cleos.py#L233) to add two keys to the owner key. It would look something like:

```
owner_auth = {
                "threshold": 1,
                "keys": [{
                    "key": "EOSxxxxxxxxxxxxxxx1",
                    "weight": 1
                },{
                    "key": "EOSxxxxxxxxxxxxxxx1",
                    "weight": 1
                }],
                "accounts": [],
                "waits": []
            }
```
The same could be done for the active key. 

To answer the your two questions I would run:
```
cleos create key -f <some_file_name>
chmod 600 <some_file_name>
```
Then I would use the [parse_key_file](https://github.com/eosnewyork/eospy/blob/c9b49f727e952a742902df9ba098dc6e21cdeb5e/eospy/utils.py#L7) to extract the private key in your python file and pass that to the push_transaction function. I am working on adding support for other signing methods but it is currently low on the priority list.

**Comment by amitsharma8891** [comment]
Thanks, @deckb for your response. I used the `cleos create key -f <some_file_name>` and generated private and public key now when I tried to create an account using these keys it throws  following error
 
> raise EOSKeyError('Must pass a class that extends the eospy.Signer class')
> eospy.exceptions.EOSKeyError: Must pass a class that extends the eospy.Signer class

and here is my create account code.
```
ce = cleos.Cleos(url=settings.BLOCKCHAIN_URL)
    key1 = generate_keys()
    key2 = generate_keys()
    print(key1)
    print(key2)

    ca = ce.create_account(creator=settings.CREATOR,
                           creator_privkey=settings.CREATOR_PRIVATE_KEY,
                           acct_name=account_name,
                           owner_key=key1['public_key'],
                            active_key=key2['public_key'],
                           stake_net='1.0000 EOS', stake_cpu='1.0000 EOS', ramkb=8, permission='active',
                           transfer=False, broadcast=True
                           )

```

Can you tell me where am I doing wrong?

Thanks

**Comment by deckb** [comment]
You need to pass an EOSKey as `creator_privkey`

See lines 35/36

https://github.com/eosnewyork/eospy/blob/master/examples/push_transaction.py#L35

**Comment by amitsharma8891** [comment]
Thanks, @deckb, it was a really great help, actually, I am trying to set multisig permission, before I was using following cleos command to set the permission: 
For active
`cleos --url https://api-kylin.eosasia.one:443 set account permission mymultisig14 active '{"threshold":2,"keys":[],"accounts":[{"permission":{"actor":"mcttoken1233","permission":"active"},"weight":1},{"permission":{"actor":"mcttoken1234","permission":"active"},"weight":1},{"permission":{"actor":"mcttoken1235","permission":"active"},"weight":1}],"waits":[]}' owner -p mymultisig14@owner
`
For owner
` cleos --url https://api-kylin.eosasia.one:443 set account permission mymultisig14 owner '{"threshold":2,"keys":[],"accounts":[{"permission":{"actor":"mcttoken1233","permission":"owner"},"weight":1},{"permission":{"actor":"mcttoken1234","permission":"owner"},"weight":1},{"permission":{"actor":"mcttoken1235","permission":"owner"},"weight":1}],"waits":[]}' -p mymultisig14@owner`


I am not able to set multisig permission, I tried your previous suggestions still no luck.

Thanks

**Comment by deckb** [comment]
I guess I was confused by what you were originally asking. What error message are you seeing when you run those commands?

**Comment by deckb** [comment]
Closed with no response
