### ISSUE TITLE
What are the potential risks using eospy EOSKey for mainnet?

### ISSUE THREAD

**Issue by shalakhin** [eosnewyork/eospy#51]
Hi!

What is the potential risk to use eospy's `EOSKey` for mainnet keys generation?

P.S. Thank you for your work on eospy and cleos behavior reproducing via Python

**Comment by deckb** [comment]
It is not recommended to use EOSKey to generate keys at this time. I have not fully vetted the process nor had anyone else take a look. I would use cleos or eosjs-ecc (https://github.com/EOSIO/eosjs-ecc)
