### ISSUE TITLE
when push transaction error:'code': 3050003, 'name': 'eosio_assert_message_exception', 'what': 'eosio_assert_message assertion failure'

### ISSUE THREAD

**Issue by Chenboxi2015** [eosnewyork/eospy#6]
function wallet_unlock raise error too

**Comment by deckb** [comment]
Could I get some code to repro the issue for push_transaction? Also I left wallet_unlock in the code but it isn't implemented as I changed my mind on whether I wanted to use keosd at all.

**Comment by Chenboxi2015** [comment]
I have found the reason raise error 'eosio_assert_message assertion failure',it's because the quantity i send is '1.000 EOS',it's should be '1.0000 EOS',but i have another question how to calculate the balance of a memo under a account ? have some ideas?

**Comment by Chenboxi2015** [comment]
@deckb do you have function to create account or validate account name ?

**Comment by deckb** [comment]
I am working on that now however currently there appears to be a bug in `abi_json_to_bin` for `newaccount` that causes some pain.  See the issue I opened for more information:

https://github.com/EOSIO/eos/issues/5629

**Comment by deckb** [comment]
Sorry I forgot to respond to this. In case you didn't see there is a function to create a new account: https://github.com/eosnewyork/eospy/blob/498ca599a388751fee589442f5d2f9e8bffb0332/eospy/cleos.py#L213
