### ISSUE TITLE
HTTPConnectionPool(host='api.pennstation.eosnewyork.io', port=7001): Max retries exceeded with url: /v1/chain/abi_json_to_bin (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x75c91050>: Failed to establish a new connection: [Errno 111] Connection refused'

### ISSUE THREAD

**Issue by muhoz** [eosnewyork/eospy#64]
Hi, i am a newbie just trying to work on EOS by testing the examples provided there. But i have an error everytime i am trying to use the create_user.py, the url provided doens't work.

**Comment by deckb** [comment]
the EOS New York team shut down the node. I would suggest trying https://eos.greymass.com for now. I will update the default.

**Comment by muhoz** [comment]
Thanks, i will try it.
