### ISSUE TITLE
Missing changelog

### ISSUE THREAD

**Issue by yawhide** [eosnewyork/eospy#68]
Howdy,

Is there a changelog anywhere that I could take a look at? I want to update from 2.0.1 to 2.1.0 but I am not super familiar with this library and what has been going on.

Thanks

**Comment by deckb** [comment]
I have whipped up some release notes (https://github.com/eosnewyork/eospy/releases/tag/v2.1.0) for you. Let me know if you have any additional questions.

**Comment by yawhide** [comment]
this is perfect, thank you!
