### ISSUE TITLE
ImportError: cannot import name 'InvalidKeyFile' from 'eospy.exceptions'

### ISSUE THREAD

**Issue by BarrowHill** [eosnewyork/eospy#71]
Hello dear admin, could you help with this please?
   Checking installation
pip install eospy
Requirement already satisfied: eospy in c:\python312\lib\site-packages (0.0.2)
Requirement already satisfied: requests in c:\python312\lib\site-packages (from eospy) (2.31.0)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\python312\lib\site-packages (from requests->eospy) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\python312\lib\site-packages (from requests->eospy) (3.6)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\python312\lib\site-packages (from requests->eospy) (2.1.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\python312\lib\site-packages (from requests->eospy) (2023.11.17)
 Running my code and get this error
    from eospy.exceptions import InvalidKeyFile
ImportError: cannot import name 'InvalidKeyFile' from 'eospy.exceptions' (C:\Python312\Lib\site-packages\eospy\exceptions.py)
 Then I opening that file and see
only this 3 classes
class BaseError(BaseException):
    pass

class ParameterError(BaseError):
    pass

class HostConnectionError(BaseError):
    pass

Then I am openingoriginal file from here https://github.com/eosnewyork/eospy/blob/master/eospy/exceptions.py and see there 49 lines of code. I am copying that and replacing my "broken" exceptions.py (by the way, Uninstall and install again is not helping)
Now I get this error
    from .exceptions import ParameterError, HostConnectionError
ImportError: cannot import name 'ParameterError' from 'eospy.exceptions' (C:\Python312\Lib\site-packages\eospy\exceptions.py)
I am opening that file and there is no class called 'ParameterError'.
Could you fix this 2 issues please?

**Comment by deckb** [comment]
NOTE this library is defunct. Please use another library to connect to your network.

The eospy library is not the correct library to install. Per the README you should install libeospy. Try uninstalling eospy and installing libeospy
